export const VIEW_CODE = {
	PUBLIC: "PUBLIC",

	// role
	APP_ROLE_VIEW: "APP_ROLE_VIEW",
	APP_ROLE_CREATE: "APP_ROLE_CREATE",
	APP_ROLE_EDIT: "APP_ROLE_EDIT",
	APP_ROLE_DELETE: "APP_ROLE_DELETE",

	// actions
	APP_ACTION_VIEW: "APP_ACTION_VIEW",
	APP_ACTION_CHANGE_POSITION: "APP_ACTION_CHANGE_POSITION",
	APP_ACTION_CREATE: "APP_ACTION_CREATE",
	APP_ACTION_EDIT: "APP_ACTION_EDIT",
	APP_ACTION_DELETE: "APP_ACTION_DELETE",
	APP_API_LOG: "APP_API_LOG",
	APP_CONFIG: "APP_CONFIG",

	// profile
	MY_USER_ACTIONS: "MY_USER_ACTIONS",
	MY_USER_PROFILE: "MY_USER_PROFILE",

	// user
	USER_CREATE: "USER_CREATE",
	USER_SEARCH_HRM: "USER_SEARCH_HRM",
	ROLE_ASSIGN_USER: "ROLE_ASSIGN_USER",
	USER_EDIT: "USER_EDIT",
	USER_VIEW: "USER_VIEW",
	USER_DELETE: "USER_DELETE",
	USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
	USER_LOCK: "USER_LOCK",
	USER_ACTIVE: "USER_ACTIVE",

	// project
	PROJECT_LIST: "PROJECT_LIST",
	PROJECT_CREATE: "PROJECT_CREATE",
	PROJECT_EDIT: "PROJECT_EDIT",
	PROJECT_DETAIL: "PROJECT_DETAIL",
	PROJECT_DETAIL_ADD_MEMBER: "PROJECT_DETAIL_ADD_MEMBER",
	PROJECT_DETAIL_REMOVE_MEMBER: "PROJECT_DETAIL_REMOVE_MEMBER",

	// module
	MODULE_LIST: "MODULE_LIST",
	MODULE_CREATE: "MODULE_CREATE",
	MODULE_DELETE: "MODULE_DELETE",
	MODULE_EDIT: "MODULE_EDIT",
	MODULE_DETAIL: "MODULE_DETAIL",

	VIEW_DASHBOARD: "VIEW_DASHBOARD",

	//error
	ERROR_LIST_BY_USER: "ERROR_LIST_BY_USER",
	ERROR_LIST_ALL: "ERROR_LIST_ALL",

	//export
	PROJECT_LIST_EXPORT: "PROJECT_LIST_EXPORT",
	MODULE_LIST_EXPORT: "MODULE_LIST_EXPORT",
	ERROR_LIST_EXPORT: "ERROR_LIST_EXPORT",
	ERROR_LIST_ALL_EXPORT: "ERROR_LIST_ALL_EXPORT",

	SERVER_MONITOR: "SERVER_MONITOR",
	QUERY_DATA_STATUS: "QUERY_DATA_STATUS",
};

export const DEFAULT_ROLE_LEVEL = 5;
